name: mysqldumper Coverage
on: [push, pull_request]
jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: '^1.19.1'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Coverage
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make coverage
        bash <(curl -s https://codecov.io/bash) -f "!mock.go" -t 0f6e1ff6-4644-4bc8-98d5-3e269454be61
